apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: mine
spec:
  containers:
  - name: my-container
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
